#!/bin/bash
#
#  Tester Helper by Litovchenko Alexandr
#  Arguments:
#  --list -l        - list of all feature files and theire apps
#  --start -s TAG   - start test feature with tag TAG
#

if [[ $1 = '--list' || $1 = '-l' ]]; then
    find ./test/features/apps/ -type f | xargs -L 1 basename | sed 's/\.feature$//'
    exit;
fi

if [[ $1 = '--start' || $1 = '-s' ]]; then
    if [ -z `ps -C start_dashboard.sh -o pid=` ]; then #If Sahi Dashboat not run
        [ ! -e ./log/sahi.log ] && touch ./log/sahi.log
        LOGFILE="`pwd`/log/sahi.log";
        [ ! -w $LOGFILE ] && chmod u+w $LOGFILE
        echo "Use log file $LOGFILE"
        cd /home/zed/bin/sahi/userdata/bin/;
        ./start_dashboard.sh &> $LOGFILE &
        cd -
        echo 'starting sahi dashboat'
    fi
    ./behat --tags $2
    exit;
fi

