# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/12-Filters

oneuse:
  class: tfOneUsePassFilter
autologin:
  class: tfDebugAutologinFilter
rendering: ~
security:  
  class: tfSmppSecurityFilter
cache:     ~
execution: ~
