subsystem_1:
  name: "заявки"
  choices:
    foreign_auth: "Может пользоваться авторизующей ссылкой"
    can_access_admin_panel: "Может пользоваться панелью управления"
    super_can_get_report: "Может получать отчеты"
    super_can_index: "[Все заявки] Может смотреть список заявок"
    super_can_show: "[Все заявки] Может смотреть заявку"
    super_can_modify_content: "[Все заявки] Может изменять содержимое заявки"
    super_can_change_urgent: "[Все заявки] Может устанавливать срочность заявки"
    super_can_change_topic: "[Все заявки] Может изменять тему заявки"
    super_can_change_executor: "[Все заявки] Может изменять исполнителя заявки"
    super_can_change_parent: "[Все заявки] Может изменять родительскую заявку"
    super_can_create_dependency: "[Все заявки] Может добавлять зависимость"
    super_can_add_commentary: "[Все заявки] Может добавлять комментарий к заявке"
    super_can_create_file: "[Все заявки] Может добавлять файл"
    super_can_edit_file: "[Все заявки] Может изменять файл"
    super_can_delete_file: "[Все заявки] Может удалять файл"
    super_can_get_file: "[Все заявки] Может скачивать файл"
    super_can_complete: "[Все заявки] Может ставить статус «Выполнена»"
    super_can_close: "[Все заявки] Может ставить статус «Закрыта»"
    super_can_open: "[Все заявки] Может открывать закрытые заявки"
    can_create_ticket: "Может добавлять заявку"
    can_modify_content: "Может изменять содержимое заявки"
    can_change_topic: "Может изменять тему заявки"
    can_change_executor: "Может изменять исполнителя заявки"
    can_set_parent: "Может изменять родительскую заявку"
    can_create_dependency: "Может добавлять зависимость"
    can_add_commentary: "Может добавлять комментарий к заявке"
    can_create_file: "Может добавлять файл"
    can_edit_file: "Может изменять файл"
    can_delete_file: "Может удалять файл"
    can_load_topic_tree: "Может пользоваться деревом тем"
    can_load_topic_tree_with_inactive: "Может пользоваться деревом тем с неактивными темами"
    can_index_topic: "Может управлять деревом тем"
    can_show_topic: "Может смотреть тему"
    can_create_topic: "Может добавлять тему"
    can_edit_topic: "Может изменять тему"
    can_delete_topic: "Может удалять тему"
    can_create_topic_staff: "Может добавлять роль темы"
    can_edit_topic_staff: "Может изменять роль темы"
    can_delete_topic_staff: "Может удалять роль темы"
    can_transfer_topic_staff: "Может передавать заявки из роли темы"
subsystem_2:
  name:  "реквизиты"
  choices:
    can_show_organization_own: "Может смотреть организации типа «Своя»"
    can_create_organization_own: "Может создавать организации типа «Своя»"
    can_edit_organization_own: "Может изменять организации типа «Своя»"
    can_delete_organization_own: "Может удалять организации типа «Своя»"
    can_show_organization_private: "Может смотреть организации типа «Приватная»"
    can_create_organization_private: "Может создавать организации типа «Приватная»"
    can_edit_organization_private: "Может изменять организации типа «Приватная»"
    can_delete_organization_private: "Может удалять организации типа «Приватная»"
    can_show_organization_public: "Может смотреть организации типа «Публичная»"
    can_create_organization_public: "Может создавать организации типа «Публичная»"
    can_edit_organization_public: "Может изменять организации типа «Публичная»"
    can_delete_organization_public: "Может удалять организации типа «Публичная»"
    can_show_organization_category: "Может просматривать категории организаций»"
    can_create_organization_category: "Может создавать категории организаций»"
    can_edit_organization_category: "Может редактировать категории организаций»"
    can_delete_organization_category: "Может удалять категории организаций»"
subsystem_3:
  name:  "системные настройки"
  choices:
    can_show_group: "Может смотреть группы пользователей"
    can_create_group: "Может создавать группы пользователей"
    can_edit_group: "Может изменять группы пользователей"
    can_delete_group: "Может удалять группы пользователей"
    can_show_config_files: "Может смотреть конфигурационные файлы"
    can_edit_config_files: "Может редактировать конфигурационные файлы"
    can_show_templates: "Может смотреть шаблоны"
    can_edit_templates: "Может редактировать шаблоны"
    can_observe_machines: "Может следить за машинами"
